name: Build BREXX

on: [push]

jobs:

#**************************************************#
  build-cms:
    name: Build for CMS
    runs-on: [ubuntu-latest]
    container: rosspatterson/vm370:builder
    outputs:
      BUILD_DATE: ${{ steps.build.outputs.BUILD_DATE }}
      REXX_LEVEL: ${{ steps.build.outputs.REXX_LEVEL }}
      VERSION_STRING: ${{ steps.build.outputs.VERSION_STRING }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Move Source
      run: |
        mkdir /opt/hercules/vm370/io
        mv * /opt/hercules/vm370/io
      shell: bash

    - name: Build
      id: build
      working-directory: /opt/hercules/vm370
      run: |
        chmod -R ugo+rw *
        . /opt/hercules/vm370/setup.sh
        hercules -f hercules.conf -d >/dev/null 2>/dev/null &
        cd io
        chmod +x cmsbuild.sh
        echo "Running CMSBUILD"
        ./cmsbuild.sh
      shell: bash

    - name: Get Executable
      run: |
        mkdir -p exe
        cp /opt/hercules/vm370/io/brexxbin.aws exe
        cp /opt/hercules/vm370/io/brexxsrc.aws exe
        cp /opt/hercules/vm370/io/brexxbin.vmarc exe
        cp /opt/hercules/vm370/io/brexxsrc.vmarc exe
        cp /opt/hercules/vm370/io/LICENSE exe
        cp /opt/hercules/vm370/io/README.md exe
        cp /opt/hercules/vm370/io/changelog.txt exe
        cp /opt/hercules/vm370/gccbrx.cckd exe
        cp /opt/hercules/vm370/io/maintc.direct exe
        cp /opt/hercules/vm370/io/tools/newbrexx.exec exe
        chmod -R ugo+r exe
      shell: bash

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: BREXX
        path: ./exe

#**************************************************#
  test-install:
    strategy:
      matrix:
        inst_type: ["bin-tape", "bin-vmarc", "dasd", "src-tape", "src-vmarc"]
      fail-fast: false
    name: Test install via ${{ matrix.inst_type }}
    needs: [build-cms]
    runs-on: [ubuntu-latest]
    container: rosspatterson/vm370:builder
    steps:
      - name: Checkout (minimal)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: |
            cmsinst.sh
          sparse-checkout-cone-mode: false

      - name: Move Source
        run: |
          mkdir -p /opt/hercules/vm370/io/BREXX
          mv cmsinst.sh /opt/hercules/vm370/io
        shell: bash

      - name: Get CMS binary
        uses: actions/download-artifact@v4
        with:
          name: BREXX
          path: /opt/hercules/vm370/io/BREXX

      - name: Install
        working-directory: /opt/hercules/vm370
        env:
          BUILD_DATE: ${{needs.build-cms.outputs.BUILD_DATE}}
          VERSION_STRING: ${{needs.build-cms.outputs.VERSION_STRING}}
        run: |
          chmod -R ugo+rw *
          . /opt/hercules/vm370/setup.sh
          hercules -f hercules.conf -d >/dev/null 2>/dev/null &
          cd io
          chmod +x cmsinst.sh
          echo "Running CMSINST ${{ matrix.inst_type }}"
          ./cmsinst.sh "${{ matrix.inst_type }}" "$VERSION_STRING" "$BUILD_DATE"
        shell: bash

#**************************************************#
  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Release
    needs: [build-cms, test-install]
    runs-on: [ubuntu-latest]
    steps:
      - name: Get CMS binary
        uses: actions/download-artifact@v4
        with:
          name: BREXX
          path: BREXX

      - name: ZIP CMS binary
        run:
          zip -r BREXX.zip BREXX

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload Release Asset - CMS
        id: upload-release-asset-CMS
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./BREXX.zip
          asset_name: BREXX.zip
          asset_content_type: application/zip
